const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');

const readJson = (file, fallback) => { try { return JSON.parse(fs.readFileSync(file, 'utf8')); } catch { return fallback; } };
const writeJsonAtomic = (file, value) => { const temp = `${file}.${process.pid}.tmp`; fs.writeFileSync(temp, `${JSON.stringify(value, null, 2)}\n`, 'utf8'); fs.renameSync(temp, file); };
const string = (value, max = 200) => String(value || '').trim().slice(0, max);
const id = (value) => string(value, 80) || crypto.randomUUID();
const array = (value) => Array.isArray(value) ? value : [];

class ProductivityHub {
  constructor(dataDirectory) { this.file = path.join(dataDirectory, 'productivity.json'); this.notifiedFile = path.join(dataDirectory, 'productivity-notified.json'); fs.mkdirSync(dataDirectory, { recursive: true }); }
  snapshot() { const value = readJson(this.file, {}); return { courseSchedule: { enabled: value.courseSchedule?.enabled === true, entries: array(value.courseSchedule?.entries).map((entry) => ({ id: id(entry.id), title: string(entry.title), startAt: string(entry.startAt, 40), endAt: string(entry.endAt, 40), reminderMinutes: Math.min(180, Math.max(0, Math.floor(Number(entry.reminderMinutes) || 10))) })).filter((entry) => entry.title && !Number.isNaN(Date.parse(entry.startAt))) }, journal: { enabled: value.journal?.enabled === true, aiReadEnabled: value.journal?.aiReadEnabled === true, entries: array(value.journal?.entries).map((entry) => ({ id: id(entry.id), date: string(entry.date, 10), text: string(entry.text, 20_000) })).filter((entry) => entry.date && entry.text) }, goals: { enabled: value.goals?.enabled === true, entries: array(value.goals?.entries).map((entry) => ({ id: id(entry.id), title: string(entry.title), stage: string(entry.stage), progress: Math.min(100, Math.max(0, Math.floor(Number(entry.progress) || 0))), deadline: string(entry.deadline, 10) })).filter((entry) => entry.title) }, importantDates: { enabled: value.importantDates?.enabled === true, entries: array(value.importantDates?.entries).map((entry) => ({ id: id(entry.id), title: string(entry.title), type: ['exam', 'birthday', 'deadline', 'anniversary'].includes(entry.type) ? entry.type : 'deadline', date: string(entry.date, 10) })).filter((entry) => entry.title && !Number.isNaN(Date.parse(`${entry.date}T00:00:00`))) } }; }
  replace(moduleName, value) { if (!['courseSchedule', 'journal', 'goals', 'importantDates'].includes(moduleName)) throw new Error('未知生产力模块'); const current = this.snapshot(), previous = current[moduleName]; current[moduleName] = { ...previous, ...value, entries: array(value.entries) }; writeJsonAtomic(this.file, current); const next = this.snapshot()[moduleName], events = []; if (moduleName === 'goals') { const before = new Map(previous.entries.map((entry) => [entry.id, entry.progress])); for (const entry of next.entries) if (before.get(entry.id) !== entry.progress) events.push({ type: 'GOAL_PROGRESS_UPDATED', payload: { id: entry.id, title: entry.title, progress: entry.progress } }); } return { module: next, events }; }
  todayJournal(now = new Date()) { const day = now.toISOString().slice(0, 10), journal = this.snapshot().journal; if (!journal.enabled || !journal.aiReadEnabled) throw new Error('请先启用日记模块和 AI 读取权限'); const entry = journal.entries.find((item) => item.date === day); if (!entry) throw new Error('今天还没有日记'); return entry; }
  tick(now = new Date()) { const snapshot = this.snapshot(), notified = readJson(this.notifiedFile, {}), events = [], nowMs = now.getTime(), day = now.toISOString().slice(0, 10); if (snapshot.courseSchedule.enabled) for (const entry of snapshot.courseSchedule.entries) { const start = Date.parse(entry.startAt), key = `course:${entry.id}:${entry.startAt}`; if (!notified[key] && nowMs >= start - entry.reminderMinutes * 60_000 && nowMs <= start + 60_000) { notified[key] = now.toISOString(); events.push({ type: 'COURSE_STARTING', payload: { id: entry.id, title: entry.title, startAt: entry.startAt, minutes: Math.max(0, Math.ceil((start - nowMs) / 60_000)) } }); } } if (snapshot.importantDates.enabled) for (const entry of snapshot.importantDates.entries) { const target = Date.parse(`${entry.date}T00:00:00`), days = Math.ceil((target - Date.parse(`${day}T00:00:00`)) / 86_400_000), key = `date:${entry.id}:${day}`; if (!notified[key] && [0, 1, 3, 7, 30].includes(days)) { notified[key] = now.toISOString(); events.push({ type: 'IMPORTANT_DATE_APPROACHING', payload: { id: entry.id, title: entry.title, date: entry.date, dateType: entry.type, days } }); } } if (events.length) writeJsonAtomic(this.notifiedFile, Object.fromEntries(Object.entries(notified).slice(-2000))); return events; }
}

module.exports = { ProductivityHub };
